#!/usr/bin/env python3

import socket
import sys

host = sys.argv[1]
port = int(sys.argv[2])

s = socket.socket(
    socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(0.2)

r = 1

try:
    r = s.connect((host, port))
except OSError:
    r = 1
finally:
    s.close()

sys.exit(r)
